
from algorithms.algorithm_dfs import algorithm_dfs
from algorithms.algorithm_bfs import algorithm_bfs
from algorithms.algorithm_ucs import algorithm_ucs
from algorithms.algorithm_gbfs import algorithm_greedy_bfs_heuristic_1, algorithm_greedy_bfs_heuristic_2
from algorithms.algorithm_astar import algorithm_astar_heuristic_1, algorithm_astar_heuristic_2
from algorithms.algorithm_advance import algorithm_bonus_astar, algorithm_handle_bonus_pickup, algorithm_handle_all


